platform :ios, '8.0'
target 'Meow' do
use_frameworks!
pod 'AFNetworking', '~>3.1.0'
pod 'MJRefresh', '~>3.1.12'
pod 'SDWebImage', '~>3.7'
pod 'MJExtension', '~>3.0.13'
pod 'MBProgressHUD', '~>1.0.0'
pod 'YZDisplayViewController', '~>1.0.6'
pod 'ReactiveObjC', '~>2.1.2'
pod 'UITableView+FDTemplateLayoutCell', '~>1.5.beta'
pod 'LTNavigationBar', '~>2.1.9'
pod 'Masonry', '~>1.0.2'
pod 'SDCycleScrollView', '~>1.64'
pod 'JZNavigationExtension', '~>1.5.0.1'
pod 'RongCloudIM', '~>2.8.4'
pod 'GPUImage', '~>0.1.7'
pod 'TAPageControl', '~>0.2.0'
pod 'IQKeyboardManager', '~> 4.0.9'
pod 'YZHeaderScaleImage', '~> 1.0.1'
pod 'YTKKeyValueStore'
pod 'YTKNetwork'
pod 'YYWebImage'
pod 'YYModel'
end
